// export const oraLineTypes = {
//     "A266FF2A662E84b639DA": [{
//             "ID": "1",
//             "Code": "0",
//             "Style": "0",
//             "Weight": "2"
//         },
//         {
//             "ID": "2",
//             "Code": "1",
//             "EngName": "ndVhvdsj",
//             "Style": "1",
//             "Weight": "2",
//             "Name": "دیواریست"
//         },
//         {
//             "ID": "3",
//             "Code": "2",
//             "EngName": "ndVhvdsj lajvK",
//             "Style": "2",
//             "Weight": "2",
//             "Name": "دیواریست مشترک"
//         },
//         {
//             "ID": "4",
//             "Code": "3",
//             "EngName": "ndVhv fi ndVhv hsj",
//             "Style": "3",
//             "Weight": "2",
//             "Name": "دیوار به دیوار است"
//         },
//         {
//             "ID": "5",
//             "Code": "4",
//             "EngName": "nvf hsj",
//             "Style": "4",
//             "Weight": "2",
//             "Name": "درب است",
//             "Block": "D"
//         },
//         {
//             "ID": "6",
//             "Code": "5",
//             "EngName": "nvf V ndVhv hsj",
//             "Style": "5",
//             "Weight": "2",
//             "Name": "درب و دیوار است",
//             "Block": "DD"
//         },
//         {
//             "ID": "7",
//             "Code": "6",
//             "EngName": "kvni hdsj",
//             "Style": "6",
//             "Weight": "2",
//             "Name": "نرده ایست"
//         },
//         {
//             "ID": "8",
//             "Code": "7",
//             "EngName": "PdavtjGd hsj",
//             "Style": "7",
//             "Weight": "2",
//             "Name": "پیشرفتگی است"
//         },
//         {
//             "ID": "9",
//             "Code": "8",
//             "EngName": "ndVhvdsj PdavtjGd",
//             "Style": "0",
//             "Weight": "1",
//             "Name": "دیواریست پیشرفتگی"
//         },
//         {
//             "ID": "10",
//             "Code": "9",
//             "EngName": "kvni hdsj PdavtjGd",
//             "Style": "1",
//             "Weight": "1",
//             "Name": "نرده ایست پیشرفتگی"
//         },
//         {
//             "ID": "11",
//             "Code": "10",
//             "EngName": "lvcdsj",
//             "Style": "2",
//             "Weight": "1",
//             "Name": "مرزیست"
//         },
//         {
//             "ID": "12",
//             "Code": "11",
//             "EngName": "ndVhv V PkJvi hsj",
//             "Style": "3",
//             "Weight": "1",
//             "Name": "دیوار و پنجره است",
//             "Block": "DP"
//         },
//         {
//             "ID": "13",
//             "Code": "12",
//             "EngName": "5-ndVhv V nvc hkrxhu fi uvq PkJ shkjd ljv hsj",
//             "Style": "4",
//             "Weight": "1",
//             "Name": "5-دیوار و درز انقطاع به عرض پنج سانتی متر است"

//         },
//         {
//             "ID": "14",
//             "Code": "13",
//             "EngName": "7-ndVhv Vnvc hkrxhu fi uvq itj shkjd ljv hsj",
//             "Style": "5",
//             "Weight": "1",
//             "Name": "7-دیوار ودرز انقطاع به عرض هفت سانتی متر است"
//         },
//         {
//             "ID": "15",
//             "Code": "14",
//             "EngName": "10-ndVhv V nvc hkrxhu fi uvq ni shkjd ljv hsj",
//             "Style": "6",
//             "Weight": "1",
//             "Name": "10-دیوار و درز انقطاع به عرض ده سانتی متر است"
//         },
//         {
//             "ID": "16",
//             "Code": "15",
//             "EngName": "15-ndVhv V nvc hkrxhu fi uvq Phkcni shkjd ljv hsj",
//             "Style": "7",
//             "Weight": "1",
//             "Name": "15-دیوار و درز انقطاع به عرض پانزده سانتی متر است"
//         },
//         {
//             "ID": "17",
//             "Code": "16",
//             "EngName": "fi ndVhv",
//             "Style": "0",
//             "Weight": "3",
//             "Name": "به دیوار"
//         },
//         {
//             "ID": "18",
//             "Code": "17",
//             "EngName": "nvf V ndVhv V PkJvi hd hsj",
//             "Style": "1",
//             "Weight": "3",
//             "Name": "درب و دیوار و پنجره ای است",
//             "Block": "DDP"
//         },
//         {
//             "ID": "19",
//             "Code": "18",
//             "EngName": "ox tvqd hsj",
//             "Style": "2",
//             "Weight": "3",
//             "Name": "خط فرضی است"
//         },
//         {
//             "ID": "20",
//             "Code": "19",
//             "EngName": "ndVhv V PkJvi  fwVvj PdavtjGd fi tqhd odhfhk",
//             "Style": "3",
//             "Weight": "3",
//             "Name": "دیوار و پنجره  بصورت پیشرفتگی به فضای خیابان"
//         },
//         {
//             "ID": "21",
//             "Code": "20",
//             "EngName": "nvf V ndVhv Vgfi fhgKk",
//             "Style": "4",
//             "Weight": "3",
//             "Name": "درب و دیوار ولبه بالکن"
//         },
//         {
//             "ID": "22",
//             "Code": "21",
//             "EngName": "ndVhv Vgfi fhgKk",
//             "Style": "5",
//             "Weight": "3",
//             "Name": "دیوار ولبه بالکن"
//         },
//         {
//             "ID": "23",
//             "Code": "22",
//             "EngName": "7.5-ndVhv Vnvc hkrxhu fi uvq itj Vkdl shkjd ljv hsj",
//             "Style": "6",
//             "Weight": "3",
//             "Name": "7.5-دیوار ودرز انقطاع به عرض هفت ونیم سانتی متر است"
//         },
//         {
//             "ID": "24",
//             "Code": "23",
//             "EngName": "vlP",
//             "Style": "7",
//             "Weight": "3",
//             "Name": "رمپ"
//         },
//         {
//             "ID": "25",
//             "Code": "24",
//             "EngName": "ndVhv fi tqhd odhfhk",
//             "Style": "0",
//             "Weight": "4",
//             "Name": "دیوار به فضای خیابان"
//         },
//         {
//             "ID": "26",
//             "Code": "25",
//             "EngName": "ndVhv V PkJvi rslj PdavtjGd shojlhk",
//             "Style": "1",
//             "Weight": "4",
//             "Name": "دیوار و پنجره قسمت پیشرفتگی ساختمان"
//         },
//         {
//             "ID": "27",
//             "Code": "26",
//             "EngName": "ndVhvdsj fwVvj Po",
//             "Style": "2",
//             "Weight": "4",
//             "Name": "دیواریست بصورت پخ"
//         },
//         {
//             "ID": "28",
//             "Code": "27",
//             "EngName": "nv V PkJvi",
//             "Style": "3",
//             "Weight": "4",
//             "Name": "در و پنجره"
//         },
//         {
//             "ID": "29",
//             "Code": "28",
//             "EngName": "ndVhv jlhl adai hd",
//             "Style": "4",
//             "Weight": "4",
//             "Name": "دیوار تمام شیشه ای"
//         },
//         {
//             "ID": "30",
//             "Code": "29",
//             "EngName": "kvni V ndVhv fhgKk",
//             "Style": "5",
//             "Weight": "4",
//             "Name": "نرده و دیوار بالکن"
//         },
//         {
//             "ID": "31",
//             "Code": "30",
//             "EngName": "kdl ndVhv JgVd fhgKk",
//             "Style": "6",
//             "Weight": "4",
//             "Name": "نیم دیوار جلوی بالکن"
//         },
//         {
//             "ID": "32",
//             "Code": "31",
//             "EngName": "ndVhv V PkJvi V gfi fhgKk",
//             "Style": "7",
//             "Weight": "4",
//             "Name": "دیوار و پنجره و لبه بالکن"
//         },
//         {
//             "ID": "33",
//             "Code": "32",
//             "EngName": " ndVhv V PkJvi fi wVvj Po",
//             "Style": "0",
//             "Weight": "5",
//             "Name": "دیوار و پنجره به صورت پخ"
//         },
//         {
//             "ID": "34",
//             "Code": "33",
//             "EngName": "ndVhvdsj fwVvj lVvf",
//             "Style": "1",
//             "Weight": "5",
//             "Name": "دیواریست بصورت مورب"
//         },
//         {
//             "ID": "35",
//             "Code": "34",
//             "EngName": "Pd fi Pd",
//             "Style": "2",
//             "Weight": "5",
//             "Name": "پی به پی"
//         },
//         {
//             "ID": "36",
//             "Code": "35",
//             "EngName": "Pd fi ndVhv",
//             "Style": "3",
//             "Weight": "5",
//             "Name": "پی به دیوار"
//         },
//         {
//             "ID": "37",
//             "Code": "36",
//             "EngName": "ndVhv fi Pd",
//             "Style": "4",
//             "Weight": "5",
//             "Name": "دیوار به پی"
//         },
//         {
//             "ID": "38",
//             "Code": "37",
//             "EngName": "Pd hsj",
//             "Style": "5",
//             "Weight": "5",
//             "Name": "پی است"
//         },
//         {
//             "ID": "39",
//             "Code": "38",
//             "EngName": "ndVhvdsj fi tqhd lpVxi lahud",
//             "Style": "6",
//             "Weight": "5",
//             "Name": "دیواریست به فضای محوطه مشاعی"
//         },
//         {
//             "ID": "40",
//             "Code": "39",
//             "EngName": "ndVhvdsj fi lpVxi lahud",
//             "Style": "7",
//             "Weight": "5",
//             "Name": "دیواریست به محوطه مشاعی"
//         },
//         {
//             "ID": "41",
//             "Code": "40",
//             "EngName": "nvf V ndVhv fi tqhd odhfhk",
//             "Style": "0",
//             "Weight": "6",
//             "Name": "درب و دیوار به فضای خیابان"
//         },
//         {
//             "ID": "42",
//             "Code": "41",
//             "EngName": "nvf V PkJvi fi tqhd odhfhk",
//             "Style": "1",
//             "Weight": "6",
//             "Name": "درب و پنجره به فضای خیابان"
//         },
//         {
//             "ID": "43",
//             "Code": "42",
//             "EngName": "nvf V ndVhv V PkJvi fi tqhd odhfhk",
//             "Style": "2",
//             "Weight": "6",
//             "Name": "درب و دیوار و پنجره به فضای خیابان"
//         },
//         {
//             "ID": "44",
//             "Code": "43",
//             "EngName": "ji ndVhvdsj",
//             "Style": "3",
//             "Weight": "6",
//             "Name": "ته دیواریست"
//         },
//         {
//             "ID": "45",
//             "Code": "44",
//             "EngName": "ji ndVhvdsj hajvhKd",
//             "Style": "4",
//             "Weight": "6",
//             "Name": "ته دیواریست اشتراکی"
//         },
//         {
//             "ID": "46",
//             "Code": "45",
//             "EngName": "lvcdsj hajvhKd",
//             "Style": "5",
//             "Weight": "6",
//             "Name": "مرزیست اشتراکی"
//         },
//         {
//             "ID": "47",
//             "Code": "46",
//             "EngName": "Jhd nvf V ndVhvdsj",
//             "Style": "6",
//             "Weight": "6",
//             "Name": "جای درب و دیواریست"
//         },
//         {
//             "ID": "48",
//             "Code": "47",
//             "EngName": "Jh Pd hsj",
//             "Style": "7",
//             "Weight": "6",
//             "Name": "جا پی است"
//         },
//         {
//             "ID": "49",
//             "Code": "48",
//             "EngName": "Jh Pd hajvhKd hsj",
//             "Style": "0",
//             "Weight": "7",
//             "Name": "جا پی اشتراکی است"
//         },
//         {
//             "ID": "54",
//             "Code": "49",
//             "EngName": "ndVhv V nvc hkrxhu",
//             "Style": "1",
//             "Weight": "7",
//             "Name": "دیوار و درز انقطاع"
//         },
//         {
//             "ID": "55",
//             "Code": "50",
//             "EngName": "kdl ndVhv",
//             "Style": "2",
//             "Weight": "7",
//             "Name": "نیم دیوار"
//         },
//         {
//             "ID": "56",
//             "Code": "51",
//             "EngName": "nvf V ndVhv jlhl adai hd",
//             "Style": "3",
//             "Weight": "7",
//             "Name": "درب و دیوار تمام شیشه ای"
//         },
//         {
//             "ID": "57",
//             "Code": "52",
//             "EngName": "ndVhv fh PkJvi tVrhkd",
//             "Style": "4",
//             "Weight": "7",
//             "Name": "دیوار با پنجره فوقانی"
//         }
//     ]
// }

export const saLineTypeList = [{
        "id": 0,
        "Code": "0",
        "name": "خط ساده ",
        "Linetype": "VARIES",
        "Lineweight": 0.3,
        "front": "خط ساده ",
    },
    {
        "id": 2,
        "Code": "1",
        "name": "دیواریست",
        "Linetype": "CENTER",
        "Lineweight": 0.3,
        "front": "ديواريست به",
        "back": "به دیوار",
    },
    {
        "id": 3,
        "Code": "2",
        "name": "دیواریست مشترک",
        "Linetype": "DASHDOT",
        "Lineweight": 0.3,
        "front": "دیوار مشترک"
    },
    {
        "id": 4,
        "Code": "3",
        "name": "دیوار به دیوار است",
        "Linetype": "DaASHED",
        "Lineweight": 0.3,
        "front": "دیوار بدیوار",
    },
    {
        "id": 5,
        "Code": "4",
        "name": "درب است",
        "Linetype": "DIVIDE",
        "Lineweight": 0.3,
        "front": "درب است",
    },
    {
        "id": 6,
        "Code": "5",
        "name": "درب و دیوار است",
        "Linetype": "DOT",
        "Lineweight": 0.3,
        "front": "درب و دیوار",
    },
    {
        "id": 7,
        "Code": "6",
        "name": "نرده ایست",
        "Linetype": "HIDDEN",
        "Lineweight": 0.3,
        "front": "نرده ایست",
    },
    {
        "id": 8,
        "Code": "7",
        "name": "پیشرفتگی است",
        "Linetype": "PHANTOM",
        "Lineweight": 0.3,
        "front": "پیشرفتگی است",
    },
    {
        "id": 9,
        "Code": "8",
        "name": "دیواریست پیشرفتگی",
        "Linetype": "Continuous",
        "Lineweight": 0.15,
        "front": "دیواریست پیشرفتگی",
    },
    {
        "id": 10,
        "Code": "9",
        "name": "نرده ایست پیشرفتگی",
        "Linetype": "CENTER",
        "Lineweight": 0.15,
        "front": "نرده ایست پیشرفتگی",
    },
    {
        "id": 11,
        "Code": "10",
        "name": "مرزیست",
        "Linetype": "DASHDOT",
        "Lineweight": 0.15,
        "front": "مرزیست",
    },
    {
        "id": 12,
        "Code": "11",
        "name": "دیوار و پنجره است",
        "Linetype": "DASHED",
        "Lineweight": 0.15,
        "front": "دیوار و پنجره ایست",
        "back": "دیوار و پنجره ایست به"
    },
    {
        "id": 13,
        "Code": "12",
        "name": "5-دیوار و درز انقطاع به عرض پنج سانتی متر است",
        "Linetype": "DIVIDE",
        "Lineweight": 0.15,
        "front": "درز 5 سانتی متری است",
    },
    {
        "id": 14,
        "Code": "13",
        "name": "7- دیوار و درز انقطاع به عرض هفت سانتی متر است",
        "Linetype": "DOT",
        "Lineweight": 0.15,
        "front": "درز 7 سانتی متری است",
    },
    {
        "id": 15,
        "Code": "14",
        "name": "10- دیوار و درز انقطاع به عرض ده سانتی متر است",
        "Linetype": "HIDDEN",
        "Lineweight": 0.15,
        "front": "درز 10 سانتی متری است",
    },
    {
        "id": 16,
        "Code": "15",
        "name": "15- دیوار و درز انقطاع به عرض پانزده سانتی متر است",
        "Linetype": "PHANTOM",
        "Lineweight": 0.15,
        "front": "درز 15 سانتی متری است",
    }, {
        "id": 17,
        "Code": "16",
        "name": "به دیوار",
        "Linetype": "Continuous",
        "Lineweight": 0.5,
        "front": "به دیوار ",
        "back": "دیواریست به"
    },
    {
        "id": 18,
        "Code": "17",
        "name": "درب و دیوار و پنجره ای است",
        "Linetype": "CENTER",
        "Lineweight": 0.5,
        "front": "درب و دیوار و پنجره است",
    },
    {
        "id": 19,
        "Code": "18",
        "name": "خط فرضی است",
        "Linetype": "DASHDOT",
        "Lineweight": 0.5,
        "front": "خط فرضی است",
    },
    {
        "id": 20,
        "Code": "19",
        "name": "دیوار و پنجره  بصورت پیشرفتگی به فضای خیابان",
        "Linetype": "DASHED",
        "Lineweight": 0.5,
        "front": "دیوار و پنجره  بصورت پیشرفتگی به فضای خیابان",
    },
    {
        "id": 21,
        "Code": "20",
        "name": "درب و دیوار و لبه بالکن",
        "Linetype": "DIVIDE",
        "Lineweight": 0.5,
        "front": "درب و دیوار و لبه بالکن",
    },
    {
        "id": 22,
        "Code": "21",
        "name": "دیوار و لبه بالکن",
        "Linetype": "DOT",
        "Lineweight": 0.5,
        "front": "دیوار و لبه بالکن",
    },
    {
        "id": 23,
        "Code": "22",
        "name": "دیوار و درز انقطاع به عرض هفت و نیم سانتی متر است",
        "Linetype": "HIDDEN",
        "Lineweight": 0.5,
        "front": "درز 7.5 سانتی متری است"
    },
    {
        "id": 24,
        "Code": "23",
        "name": "رمپ",
        "Linetype": "PHANTOM",
        "Lineweight": 0.5,
        "front": "رمپ",
    },
    {
        "id": 25,
        "Code": "24",
        "name": "دیوار به فضای خیابان",
        "Linetype": "Continuous",
        "Lineweight": 0.7,
        "front": "دیوار به فضای خیابان",
    },
    {
        "id": 26,
        "Code": "25",
        "name": "دیوار و پنجره قسمت پیشرفتگی ساختمان",
        "Linetype": "CENTER",
        "Lineweight": 0.7,
        "front": "دیوار و پنجره قسمت پیشرفتگی ساختمان",
    },
    {
        "id": 27,
        "Code": "26",
        "name": "دیواریست بصورت پخ",
        "Linetype": "DASHDOT",
        "Lineweight": 0.7,
        "front": "دیواریست بصورت پخ",
    },
    {
        "id": 28,
        "Code": "27",
        "name": "در و پنجره",
        "Linetype": "DASHED",
        "Lineweight": 0.7,
        "front": "در و پنجره",
    },
    {
        "id": 29,
        "Code": "28",
        "name": "دیوار تمام شیشه ای",
        "Linetype": "DIVIDE",
        "Lineweight": 0.7,
        "front": "دیوار تمام شیشه ای",
    },
    {
        "id": 30,
        "Code": "29",
        "name": "نرده و دیوار بالکن",
        "Linetype": "DOT",
        "Lineweight": 0.7,
        "front": "نرده و دیوار بالکن",
    },
    {
        "id": 31,
        "Code": "30",
        "name": "نیم دیوار جلوی بالکن",
        "Linetype": "HIDDEN",
        "Lineweight": 0.7,
        "front": "نیم دیوار جلوی بالکن",
    },
    {
        "id": 32,
        "Code": "31",
        "name": "دیوار و پنجره و لبه بالکن",
        "Linetype": "PHANTOM",
        "Lineweight": 0.7,
        "front": "دیوار و پنجره و لبه بالکن",
    },
    {
        "id": 33,
        "Code": "32",
        "name": "دیوار و پنجره به صورت پخ",
        "Linetype": "Continuous",
        "Lineweight": 0.9,
        "front": "دیوار و پنجره به صورت پخ",
    },
    {
        "id": 34,
        "Code": "33",
        "name": "دیواریست بصورت مورب",
        "Linetype": "CENTER",
        "Lineweight": 0.9,
        "front": "دیواریست به صورت مورب",
    },
    {
        "id": 35,
        "Code": "34",
        "name": "پی به پی ",
        "Linetype": "DASHDOT",
        "Lineweight": 0.9,
        "front": "پی به پی ",
    },
    {
        "id": 36,
        "Code": "35",
        "name": "پی به دیوار",
        "Linetype": "DASHED",
        "Lineweight": 0.9,
        "front": "پی به دیوار",
        "back": " دیواریست به پی ",
    },
    {
        "id": 37,
        "Code": "36",
        "name": "دیوار به پی",
        "Linetype": "DIVIDE",
        "Lineweight": 0.9,
        "front": "دیواری به پی",
        "back": "پی به دیوار ",
    },
    {
        "id": 38,
        "Code": "37",
        "name": "پی است",
        "Linetype": "DOT",
        "Lineweight": 0.9,
        "front": "پی به",
        "back": "به پی",
    },
    {
        "id": 39,
        "Code": "38",
        "name": "دیواریست به فضای محوطه مشاعی",
        "Linetype": "HIDDEN",
        "Lineweight": 0.9,
        "front": "دیواریست به فضای محوطه مشاعی",
    },
    {
        "id": 40,
        "Code": "39",
        "name": "دیواریست به محوطه مشاعی",
        "Linetype": "PHANTOM",
        "Lineweight": 0.9,
        "front": "دیواریست به محوطه مشاعی",
    },
    {
        "id": 41,
        "Code": "40",
        "name": "درب و دیوار به فضای خیابان",
        "Linetype": "Continuous",
        "Lineweight": 0.2,
        "front": "درب و دیوار به فضای خیابان",
    },
    {
        "id": 42,
        "Code": "41",
        "name": "درب و پنجره به فضای خیابان",
        "Linetype": "CENTER",
        "Lineweight": 0.2,
        "front": "درب و پنجره به فضای خیابان",
    },
    {
        "id": 43,
        "Code": "42",
        "name": "درب و دیوار و پنجره به فضای خیابان",
        "Linetype": "DASHDOT",
        "Lineweight": 0.2,
        "front": "درب و دیوار و پنجره به فضای خیابان",
    },
    {
        "id": 44,
        "Code": "43",
        "name": "ته دیواریست",
        "Linetype": "DASHED",
        "Lineweight": 0.2,
        "front": "ته دیواریست",
    },
    {
        "id": 45,
        "Code": "44",
        "name": "ته دیواریست  اشتراکی",
        "Linetype": "DIVIDE",
        "Lineweight": 0.2,
        "front": "ته دیواریست  اشتراکی",
    },
    {
        "id": 46,
        "Code": "45",
        "name": "مرزیست اشتراکی",
        "Linetype": "DOT",
        "Lineweight": 0.2,
        "front": "مرزیست اشتراکی ",
    },
    {
        "id": 47,
        "Code": "46",
        "name": "جای درب و دیواریست",
        "Linetype": "HIDDEN",
        "Lineweight": 0.2,
        "front": "جای درب و دیواریست",
    },
    {
        "id": 48,
        "Code": "47",
        "name": "جا پی است",
        "Linetype": "PHANTOM",
        "Lineweight": 0.2,
        "front": "جا پی است",
    },
    {
        "id": 49,
        "Code": "48",
        "name": "جا پی اشتراکی است",
        "Linetype": "Continuous",
        "Lineweight": 0.25,
        "front": "جا پی اشتراکی است",
    },
    {
        "id": 54,
        "Code": "49",
        "name": "دیوار و درز انقطاع",
        "Linetype": "CENTER",
        "Lineweight": 0.25,
    },
    {
        "id": 55,
        "Code": "50",
        "name": "نیم دیوار ",
        "Linetype": "DASHDOT",
        "Lineweight": 0.25,
        "front": "نیم دیوار ",
    },
    {
        "id": 56,
        "Code": "51",
        "name": "درب و دیوار تمام شیشه ای",
        "Linetype": "DASHED",
        "Lineweight": 0.25,
        "front": "درب و دیوار تمام شیشه ای",
    },
    {
        "id": 57,
        "Code": "52",
        "name": "دیوار با پنجره فوقانی",
        "Linetype": "DIVIDE",
        "Lineweight": 0.25,
        "front": "دیوار با پنجره فوقانی",
    },
    {
        "id": 58,
        "Code": "-1",
        "name": "دیوار و دریچه",
        "Linetype": "DOT",
        "Lineweight": 0.25,
        "front": "دیوار  و دریچه",
    },
    {
        "id": 59,
        "Code": "-1",
        "name": "8- دیوار و درز انقطاع به عرض هشت سانتی متر است",
        "Linetype": "HIDDEN",
        "Lineweight": 0.25,
        "front": "درز 8 سانتی متری است",
    },
    {
        "id": 60,
        "Code": "-1",
        "name": "11- دیوار و درز انقطاع به عرض یازده سانتی متر است",
        "Linetype": "PHANTOM",
        "Lineweight": 0.25,
        "front": "درز 11 سانتی متری است",
    },
    {
        "id": 61,
        "Code": "-1",
        "name": "12- دیوار و درز انقطاع به عرض دوازده سانتی متر است",
        "Linetype": "Continuous",
        "Lineweight": 0.18,
        "front": "درز 12 سانتی متری است",
    },
    {
        "id": 62,
        "Code": "-1",
        "name": "9- دیوار و درز انقطاع به عرض نه سانتی متر است",
        "Linetype": "CENTER",
        "Lineweight": 0.18,
        "front": "درز 9 سانتی متری است",
    },
    {
        "id": 63,
        "Code": "-1",
        "name": "دیوار مشترک تمام شیشه ای",
        "Linetype": "DASHDOT",
        "Lineweight": 0.18,
        "front": "دیوار مشترک تمام شیشه ای",
    },
    {
        "id": 64,
        "Code": "-1",
        "name": "دیوار و بلوک شیشه ای ثابت",
        "Linetype": "DASHED",
        "Lineweight": 0.18,
        "front": "دیوار و بلوک شیشه ای ثابت",
    }
]