import type { Bounds, CadEntity, CadEntityInput, Vec2 } from '../core/types';
export const dist=(a:Vec2,b:Vec2)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
export const boundsFromPoints=(p:Vec2[]):Bounds=>p.reduce((b,q)=>({minX:Math.min(b.minX,q[0]),minY:Math.min(b.minY,q[1]),maxX:Math.max(b.maxX,q[0]),maxY:Math.max(b.maxY,q[1])}),{minX:Infinity,minY:Infinity,maxX:-Infinity,maxY:-Infinity});
export function nearestOnSegment(p:Vec2,a:Vec2,b:Vec2):Vec2{const dx=b[0]-a[0],dy=b[1]-a[1],d=dx*dx+dy*dy;if(!d)return a;const t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/d));return[a[0]+t*dx,a[1]+t*dy];}
export const unionBounds=(a:Bounds,b:Bounds):Bounds=>({minX:Math.min(a.minX,b.minX),minY:Math.min(a.minY,b.minY),maxX:Math.max(a.maxX,b.maxX),maxY:Math.max(a.maxY,b.maxY)});
export function entityBounds(value:CadEntity|CadEntityInput):Bounds{const e=value as CadEntity;if(e.type==='block-reference')return e.children.length?e.children.map(entityBounds).reduce(unionBounds):{minX:e.position[0],minY:e.position[1],maxX:e.position[0],maxY:e.position[1]};if(e.type==='point'||e.type==='text')return{minX:e.position[0],minY:e.position[1],maxX:e.position[0],maxY:e.position[1]};if(e.type==='line')return boundsFromPoints([e.start,e.end]);if(e.type==='polyline'||e.type==='polygon'||e.type==='hatch')return boundsFromPoints(e.vertices);const radial=e as Extract<CadEntity,{type:'circle'|'arc'}>;return{minX:radial.center[0]-radial.radius,minY:radial.center[1]-radial.radius,maxX:radial.center[0]+radial.radius,maxY:radial.center[1]+radial.radius};}
export function segments(e:CadEntity):[Vec2,Vec2][]{if(e.type==='line')return[[e.start,e.end]];if(e.type==='polyline'||e.type==='polygon'||e.type==='hatch'){const a:[Vec2,Vec2][]=[];for(let i=1;i<e.vertices.length;i++)a.push([e.vertices[i-1],e.vertices[i]]);if(e.closed&&e.vertices.length>2)a.push([e.vertices[e.vertices.length-1],e.vertices[0]]);return a;}return[];}
export function segmentIntersection(a:Vec2,b:Vec2,c:Vec2,d:Vec2):Vec2|undefined{const den=(a[0]-b[0])*(c[1]-d[1])-(a[1]-b[1])*(c[0]-d[0]);if(Math.abs(den)<1e-12)return;const t=((a[0]-c[0])*(c[1]-d[1])-(a[1]-c[1])*(c[0]-d[0]))/den,u=-((a[0]-b[0])*(a[1]-c[1])-(a[1]-b[1])*(a[0]-c[0]))/den;if(t>=0&&t<=1&&u>=0&&u<=1)return[a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])];}
export function hitDistance(e:CadEntity,p:Vec2):number{if(e.type==='block-reference')return Math.min(...e.children.map(x=>hitDistance(x,p)));if(e.type==='point'||e.type==='text')return dist(e.position,p);if(e.type==='circle'||e.type==='arc')return Math.abs(dist(e.center,p)-e.radius);return Math.min(...segments(e).map(([a,b])=>dist(p,nearestOnSegment(p,a,b))),Infinity);}
const normalizeAngle=(a:number)=>((a%(Math.PI*2))+Math.PI*2)%(Math.PI*2);
const angleOnArc=(a:number,start:number,end:number)=>{a=normalizeAngle(a);start=normalizeAngle(start);end=normalizeAngle(end);return start<=end?a>=start&&a<=end:a>=start||a<=end;};
export function pointInPolygon(p:Vec2,vertices:Vec2[]){let inside=false;for(let i=0,j=vertices.length-1;i<vertices.length;j=i++){const a=vertices[i],b=vertices[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
export function screenHitDistance(e:CadEntity,screen:Vec2,project:(p:Vec2)=>Vec2,zoom:number,tolerance:number):number{
  if(e.type==='block-reference')return Math.min(...e.children.map(x=>screenHitDistance(x,screen,project,zoom,tolerance)),Infinity);
  if(e.type==='point')return dist(project(e.position),screen);
  if(e.type==='text'){const p=project(e.position),co=Math.cos(e.rotation),si=Math.sin(e.rotation),dx=screen[0]-p[0],dy=screen[1]-p[1],x=dx*co-dy*si,y=dx*si+dy*co,size=Math.max(8,e.size*zoom),w=Math.max(size*.6,e.content.split('\n').reduce((m,s)=>Math.max(m,s.length),0)*size*.6),h=Math.max(size,e.content.split('\n').length*size*1.25),left=e.align==='center'?-w/2:e.align==='right'?-w:0;return x>=left-tolerance&&x<=left+w+tolerance&&y>=-h-tolerance&&y<=tolerance?0:Math.hypot(Math.max(left-x,0,x-left-w),Math.max(-h-y,0,y));}
  if(e.type==='circle'||e.type==='arc'){const c=project(e.center),edge=project([e.center[0]+e.radius,e.center[1]]),r=dist(c,edge),d=dist(c,screen),edgeDistance=Math.abs(d-r);if(e.type==='circle')return edgeDistance<=tolerance?edgeDistance:d<r?tolerance*.75:edgeDistance;const angle=Math.atan2(-(screen[1]-c[1]),screen[0]-c[0]);return angleOnArc(angle,e.startAngle,e.endAngle)?edgeDistance:Math.min(dist(screen,project([e.center[0]+Math.cos(e.startAngle)*e.radius,e.center[1]+Math.sin(e.startAngle)*e.radius])),dist(screen,project([e.center[0]+Math.cos(e.endAngle)*e.radius,e.center[1]+Math.sin(e.endAngle)*e.radius])));}
  const screenSegments=segments(e).map(([a,b])=>[project(a),project(b)]as[Vec2,Vec2]),edge=Math.min(...screenSegments.map(([a,b])=>dist(screen,nearestOnSegment(screen,a,b))),Infinity);
  if((e.type==='polygon'||e.type==='hatch')&&pointInPolygon(screen,e.vertices.map(project)))return Math.min(edge,tolerance*.75);
  return edge;
}
