import type{Vec2}from'../../cad/core/types';import type{NormalizedSegment}from'../model/SubdivisionLine';import type{SubdivisionNode}from'../model/SubdivisionNode';import type{SubdivisionEdge}from'../model/SubdivisionEdge';import{distance,type BoundaryDetectorSettings}from'./GeometryNormalizer';
type Split={segment:NormalizedSegment;at:{t:number;p:Vec2}[]};
const cross=(a:Vec2,b:Vec2)=>a[0]*b[1]-a[1]*b[0];
function intersection(a:NormalizedSegment,b:NormalizedSegment,tol:number):{ta:number;tb:number;p:Vec2}|undefined{const r:[number,number]=[a.end[0]-a.start[0],a.end[1]-a.start[1]],s:[number,number]=[b.end[0]-b.start[0],b.end[1]-b.start[1]],d:[number,number]=[b.start[0]-a.start[0],b.start[1]-a.start[1]],den=cross(r,s),lenA=Math.hypot(...r),lenB=Math.hypot(...s);if(lenA===0||lenB===0||Math.abs(den)<=1e-12*lenA*lenB)return;const ta=cross(d,s)/den,tb=cross(d,r)/den,paramEpsilon=Math.max(Number.EPSILON*32,1e-12);if(ta<-paramEpsilon||ta>1+paramEpsilon||tb<-paramEpsilon||tb>1+paramEpsilon)return;const ca=Math.max(0,Math.min(1,ta)),cb=Math.max(0,Math.min(1,tb)),pa:Vec2=[a.start[0]+r[0]*ca,a.start[1]+r[1]*ca],pb:Vec2=[b.start[0]+s[0]*cb,b.start[1]+s[1]*cb];if(distance(pa,pb)>tol)return;return{ta:ca,tb:cb,p:[(pa[0]+pb[0])/2,(pa[1]+pb[1])/2]};}
function nearestOnSegment(p:Vec2,s:NormalizedSegment):{t:number;p:Vec2;distance:number}{const dx=s.end[0]-s.start[0],dy=s.end[1]-s.start[1],length2=dx*dx+dy*dy,t=length2?Math.max(0,Math.min(1,((p[0]-s.start[0])*dx+(p[1]-s.start[1])*dy)/length2)):0,q:Vec2=[s.start[0]+dx*t,s.start[1]+dy*t];return{t,p:q,distance:distance(p,q)};}
export class BoundaryGraphBuilder{build(segments:NormalizedSegment[],settings:BoundaryDetectorSettings):{nodes:SubdivisionNode[];edges:SubdivisionEdge[];warnings:string[]}{
 const splits:Split[]=segments.map(segment=>({segment,at:[{t:0,p:segment.start},{t:1,p:segment.end}]})),repairs=new Set<string>();
 // Close drafting gaps where an endpoint almost touches the interior of another segment.
 // Adding the projected point splits the target; endpoint clustering then gives both pieces one graph node.
 for(let i=0;i<splits.length;i++)for(const endpoint of [splits[i].segment.start,splits[i].segment.end] as Vec2[])for(let j=0;j<splits.length;j++){if(i===j)continue;const q=nearestOnSegment(endpoint,splits[j].segment);if(q.t<=0||q.t>=1||q.distance<=1e-9||q.distance>settings.gapClosingTolerance)continue;splits[j].at.push({t:q.t,p:q.p});repairs.add(`${i}:${endpoint[0]},${endpoint[1]}:${j}`);}
 for(let i=0;i<splits.length;i++)for(let j=i+1;j<splits.length;j++){const q=intersection(splits[i].segment,splits[j].segment,settings.intersectionTolerance);if(q){splits[i].at.push({t:q.ta,p:q.p});splits[j].at.push({t:q.tb,p:q.p});}}
 const pieces:{a:Vec2;b:Vec2;s:NormalizedSegment}[]=[];for(const x of splits){x.at.sort((a,b)=>a.t-b.t);const unique=x.at.filter((q,i,a)=>!i||distance(q.p,a[i-1].p)>settings.intersectionTolerance);for(let i=1;i<unique.length;i++)if(distance(unique[i-1].p,unique[i].p)>=settings.minEdgeLength)pieces.push({a:unique[i-1].p,b:unique[i].p,s:x.segment});}
 const nodes:SubdivisionNode[]=[],buckets=new Map<string,number[]>(),cell=settings.endpointTolerance||1e-9;const nodeFor=(p:Vec2,source:string):number=>{const gx=Math.floor(p[0]/cell),gy=Math.floor(p[1]/cell);let found:number|undefined;for(let x=gx-1;x<=gx+1;x++)for(let y=gy-1;y<=gy+1;y++)for(const n of buckets.get(`${x},${y}`)||[])if(distance([nodes[n].x,nodes[n].y],p)<=settings.endpointTolerance){found=n;break;}if(found===undefined){found=nodes.length;nodes.push({id:`node:${found}`,x:p[0],y:p[1],connectedEdgeIds:[],sourceEntityIds:[],toleranceCluster:{representative:[p[0],p[1]],memberCount:0}});const key=`${gx},${gy}`;buckets.set(key,[...(buckets.get(key)||[]),found]);}const n=nodes[found];n.toleranceCluster.memberCount++;if(!n.sourceEntityIds.includes(source))n.sourceEntityIds.push(source);return found;};
 const edges:SubdivisionEdge[]=[],seen=new Map<string,SubdivisionEdge>();for(const p of pieces){const ai=nodeFor(p.a,p.s.sourceEntityId),bi=nodeFor(p.b,p.s.sourceEntityId);if(ai===bi)continue;const key=ai<bi?`${ai}:${bi}`:`${bi}:${ai}`,existing=seen.get(key);if(existing){if(!existing.sourceLineIds.includes(p.s.sourceLineId))existing.sourceLineIds.push(p.s.sourceLineId);if(!existing.sourceEntityIds.includes(p.s.sourceEntityId))existing.sourceEntityIds.push(p.s.sourceEntityId);continue;}const a=nodes[ai],b=nodes[bi],edge:SubdivisionEdge={id:`edge:${edges.length}`,startNodeId:a.id,endNodeId:b.id,sourceLineIds:[p.s.sourceLineId],sourceEntityIds:[p.s.sourceEntityId],layerName:p.s.layerName,length:Math.hypot(b.x-a.x,b.y-a.y),angle:Math.atan2(b.y-a.y,b.x-a.x),metadata:{sourceType:p.s.sourceType}};edges.push(edge);seen.set(key,edge);a.connectedEdgeIds.push(edge.id);b.connectedEdgeIds.push(edge.id);}
 const dangling=nodes.filter(n=>n.connectedEdgeIds.length===1).length,warnings:string[]=[];if(repairs.size)warnings.push(`Closed ${repairs.size} endpoint-to-segment gap${repairs.size===1?'':'s'} within ${settings.gapClosingTolerance} drawing units.`);if(dangling)warnings.push(`${dangling} dangling graph endpoint${dangling===1?' remains':'s remain'} after tolerance repair.`);return{nodes,edges,warnings};}}
