import type { CadEntity,CadStyle,Vec2 } from '../core/types';import { CadCamera } from '../core/CadCamera';import { CadScene } from '../core/CadScene';import { TextRenderer } from './TextRenderer';import type{SubdivisionPolygon}from'../../subdivision/model/SubdivisionPolygon';
import type{PolygonLabelPrediction}from'../../subdivision/model/PolygonLabelPrediction';import type{PolygonCategory}from'../../subdivision/model/PolygonLabel';
const VS=`attribute vec2 p;uniform vec2 size;void main(){vec2 z=p/size*2.0-1.0;gl_Position=vec4(z.x,-z.y,0,1);}`;
const FS=`precision mediump float;uniform vec4 color;void main(){gl_FragColor=color;}`;
const rgba=(hex:string,a:number):[number,number,number,number]=>{const h=hex.startsWith('#')?hex.slice(1):'ffffff';return[parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255,a];};
const cross=(a:Vec2,b:Vec2,c:Vec2)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const inTriangle=(p:Vec2,a:Vec2,b:Vec2,c:Vec2,orientation:number)=>cross(a,b,p)*orientation>=-1e-7&&cross(b,c,p)*orientation>=-1e-7&&cross(c,a,p)*orientation>=-1e-7;
function triangulate(points:Vec2[]):number[]{
 const pts=points.filter((p,i,a)=>!i||Math.hypot(p[0]-a[i-1][0],p[1]-a[i-1][1])>1e-7);if(pts.length>2&&Math.hypot(pts[0][0]-pts[pts.length-1][0],pts[0][1]-pts[pts.length-1][1])<=1e-7)pts.pop();if(pts.length<3)return[];
 const area=pts.reduce((sum,p,i)=>sum+p[0]*pts[(i+1)%pts.length][1]-pts[(i+1)%pts.length][0]*p[1],0),orientation=area>=0?1:-1,remaining=pts.map((_,i)=>i),triangles:number[]=[];let guard=pts.length*pts.length;
 while(remaining.length>3&&guard-->0){let clipped=false;for(let i=0;i<remaining.length;i++){const ai=remaining[(i-1+remaining.length)%remaining.length],bi=remaining[i],ci=remaining[(i+1)%remaining.length],a=pts[ai],b=pts[bi],c=pts[ci];if(cross(a,b,c)*orientation<=1e-7)continue;if(remaining.some(index=>index!==ai&&index!==bi&&index!==ci&&inTriangle(pts[index],a,b,c,orientation)))continue;triangles.push(...a,...b,...c);remaining.splice(i,1);clipped=true;break;}if(!clipped)return[];}
 if(remaining.length===3)triangles.push(...pts[remaining[0]],...pts[remaining[1]],...pts[remaining[2]]);return triangles;
}
export class WebGLRenderer{
  gl:WebGLRenderingContext;program:WebGLProgram;buffer:WebGLBuffer;pos:number;size:WebGLUniformLocation;color:WebGLUniformLocation;text:TextRenderer;
  constructor(public canvas:HTMLCanvasElement){const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL is not available');this.gl=gl;const shader=(t:number,s:string)=>{const x=gl.createShader(t)!;gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x)||'Shader error');return x;};this.program=gl.createProgram()!;gl.attachShader(this.program,shader(gl.VERTEX_SHADER,VS));gl.attachShader(this.program,shader(gl.FRAGMENT_SHADER,FS));gl.linkProgram(this.program);this.buffer=gl.createBuffer()!;this.pos=gl.getAttribLocation(this.program,'p');this.size=gl.getUniformLocation(this.program,'size')!;this.color=gl.getUniformLocation(this.program,'color')!;this.text=new TextRenderer(gl);}
  resize(camera:CadCamera){const d=devicePixelRatio||1,w=Math.round(this.canvas.clientWidth*d),h=Math.round(this.canvas.clientHeight*d);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}camera.setSize(this.canvas.clientWidth,this.canvas.clientHeight);this.gl.viewport(0,0,w,h);}
  draw(scene:CadScene,camera:CadCamera,selected:string[]=[],hovered?:string,preview:Vec2[]=[]){const gl=this.gl;gl.clearColor(.035,.047,.058,1);gl.clear(gl.COLOR_BUFFER_BIT);this.grid(camera);for(const e of scene.visibleEntities()){const state=selected.includes(e.id)?'selected':e.id===hovered?'hover':undefined;this.entity(e,scene.style(e,state),camera);}if(preview.length>1)this.lines(preview,scene.styles.get('construction')!,camera);this.drawTexts(scene,camera,selected,hovered);}
  overlay(polygons:SubdivisionPolygon[],camera:CadCamera,selected?:string,predictions:PolygonLabelPrediction[]=[],showLabels=false,showUnknowns=true,confidenceColors=false){const colors:Record<PolygonCategory,string>={outside_open_area:'#64748b',neighbor_property:'#a78bfa',street_or_alley:'#94a3b8',building_entrance:'#f59e0b',building_common:'#38bdf8',circulation:'#0ea5e9',lobby:'#06b6d4',ramp:'#0891b2',stair:'#0284c7',elevator:'#6366f1',unit_space:'#22c55e',room:'#16a34a',kitchen:'#65a30d',wet_space:'#3b82f6',bathroom:'#2563eb',toilet:'#1d4ed8',utility_space:'#8b5cf6',duct:'#f97316',parking:'#14b8a6',storage:'#eab308',terrace_balcony:'#84cc16',yard:'#10b981',void_lightwell:'#06b6d4',structural_column:'#78716c',service_space:'#ec4899',unknown:'#64748b'};for(const p of polygons){const prediction=predictions.find(x=>x.polygonId===p.id),category=prediction?.selectedCategory||prediction?.predictedCategory||'unknown';if(category==='unknown'&&!showUnknowns&&prediction)continue;const active=p.id===selected,base=colors[category],confidence=prediction?.confidence??.5,s:CadStyle={id:'boundary',name:'Boundary',strokeColor:active?'#fbbf24':base,strokeWidth:active?3:1.5,fillColor:active?'#f59e0b':base,fillOpacity:active ? .3 : confidenceColors ? .08+.22*confidence : .14,opacity:1,textColor:'#fff',textSize:10,dash:[],pointSize:2};this.fill(p.vertices,s,camera);this.lines(p.vertices,s,camera,true);if(showLabels&&prediction?.selectedLabelFa){const q=camera.worldToScreen(p.centroid),size=Math.max(9,Math.min(14,10*camera.zoom));this.text.draw(prediction.selectedLabelFa,q[0],q[1],size,0,rgba('#ffffff',.95),[camera.width,camera.height],'center');}}}
  private setup(color:[number,number,number,number],c:CadCamera){const gl=this.gl;gl.useProgram(this.program);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);gl.enableVertexAttribArray(this.pos);gl.vertexAttribPointer(this.pos,2,gl.FLOAT,false,0,0);gl.uniform2f(this.size,c.width,c.height);gl.uniform4fv(this.color,color);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);}
  private grid(c:CadCamera){if(c.width<1||c.height<1)return;const target=42/c.zoom,pow=10**Math.floor(Math.log10(Math.max(target,1e-12))),m=target/pow,step=pow*(m>5?10:m>2?5:m>1?2:1),a=c.screenToWorld([0,c.height]),b=c.screenToWorld([c.width,0]),minor:Vec2[][]=[];for(let x=Math.floor(a[0]/step)*step;x<=b[0];x+=step)minor.push([[x,a[1]],[x,b[1]]]);for(let y=Math.floor(a[1]/step)*step;y<=b[1];y+=step)minor.push([[a[0],y],[b[0],y]]);const gridStyle:CadStyle={id:'grid',name:'Grid',strokeColor:'#33404d',strokeWidth:.65,fillColor:'transparent',fillOpacity:0,opacity:.42,textColor:'#33404d',textSize:10,dash:[],pointSize:1};minor.forEach(l=>this.lines(l,gridStyle,c));if(a[0]<=0&&b[0]>=0)this.lines([[0,a[1]],[0,b[1]]],{...gridStyle,strokeColor:'#50708c',strokeWidth:1.1,opacity:.75},c);if(a[1]<=0&&b[1]>=0)this.lines([[a[0],0],[b[0],0]],{...gridStyle,strokeColor:'#50708c',strokeWidth:1.1,opacity:.75},c);}
  entity(e:CadEntity,s:CadStyle,c:CadCamera){if(e.type==='block-reference'){e.children.forEach(x=>this.entity(x,s,c));return;}if(e.type==='text')return;if(e.type==='point'){const p=c.worldToScreen(e.position),r=s.pointSize;this.lines([[p[0]-r,p[1]],[p[0]+r,p[1]]],s,c,false,true);this.lines([[p[0],p[1]-r],[p[0],p[1]+r]],s,c,false,true);return;}if((e.type==='polygon'||e.type==='hatch')&&s.fillColor!=='transparent')this.fill(e.vertices,s,c);if(e.type==='line')this.lines([e.start,e.end],s,c);if(e.type==='polyline'||e.type==='polygon'||e.type==='hatch')this.lines(e.vertices,s,c,e.closed);if(e.type==='circle'||e.type==='arc'){let a=e.type==='arc'?e.startAngle:0,b=e.type==='arc'?e.endAngle:Math.PI*2;if(b<a)b+=Math.PI*2;const n=Math.max(20,Math.min(512,Math.ceil((b-a)*e.radius*c.zoom/6))),pts:Vec2[]=[];for(let i=0;i<=n;i++){const q=a+(b-a)*i/n;pts.push([e.center[0]+Math.cos(q)*e.radius,e.center[1]+Math.sin(q)*e.radius]);}if(e.type==='circle'&&s.fillColor!=='transparent')this.fill([e.center,...pts],s,c);this.lines(pts,s,c);}}
  fill(points:Vec2[],s:CadStyle,c:CadCamera){if(points.length<3)return;const tri=triangulate(points.map(p=>c.worldToScreen(p)));if(!tri.length)return;this.setup(rgba(s.fillColor,s.opacity*s.fillOpacity),c);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array(tri),this.gl.STREAM_DRAW);this.gl.drawArrays(this.gl.TRIANGLES,0,tri.length/2);}
  lines(points:Vec2[],s:CadStyle,c:CadCamera,closed=false,screen=false){let pts=screen?points:points.map(p=>c.worldToScreen(p));if(closed&&pts.length)pts=[...pts,pts[0]];const segments:[Vec2,Vec2][]=[];for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i];if(!s.dash.length){segments.push([a,b]);continue;}const len=Math.hypot(b[0]-a[0],b[1]-a[1]);let at=0,n=0,draw=true;while(at<len){const next=Math.min(len,at+Math.max(1,s.dash[n%s.dash.length]||4));if(draw)segments.push([[a[0]+(b[0]-a[0])*at/len,a[1]+(b[1]-a[1])*at/len],[a[0]+(b[0]-a[0])*next/len,a[1]+(b[1]-a[1])*next/len]]);at=next;n++;draw=!draw;}}
    const tri:number[]=[],half=Math.max(.55,s.strokeWidth/2);for(const[a,b]of segments){const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);if(len<.001)continue;const nx=-dy/len*half,ny=dx/len*half,p0:[number,number]=[a[0]+nx,a[1]+ny],p1:[number,number]=[a[0]-nx,a[1]-ny],p2:[number,number]=[b[0]+nx,b[1]+ny],p3:[number,number]=[b[0]-nx,b[1]-ny];tri.push(...p0,...p1,...p2,...p2,...p1,...p3);}if(!tri.length)return;this.setup(rgba(s.strokeColor,s.opacity),c);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array(tri),this.gl.STREAM_DRAW);this.gl.drawArrays(this.gl.TRIANGLES,0,tri.length/2);}
  drawTexts(scene:CadScene,c:CadCamera,selected:string[]=[],hovered?:string){const draw=(e:CadEntity,s:CadStyle)=>{if(e.type==='block-reference'){e.children.forEach(x=>draw(x,s));return;}if(e.type==='text'){const p=c.worldToScreen(e.position),size=Math.round(Math.max(8,Math.min(96,e.size*c.zoom)));this.text.draw(e.content,p[0],p[1],size,e.rotation,rgba(s.textColor,s.opacity),[c.width,c.height],e.align);}};for(const e of scene.visibleEntities())draw(e,scene.style(e,selected.includes(e.id)?'selected':e.id===hovered?'hover':undefined));}
}
